openai_api_key = "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"

artbl_access_token = "patIU0zTwBb1fcIMU.1b403afe42ac6a8c1fc13710692cb80cb388142e2d651975d186bd2a0e83117f"

artbl_base_id = "appDeTieKcBrzSoAG"


